# Generated by Django 3.1.2 on 2020-10-30 06:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('arkid_meta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_active_time',
            field=models.DateTimeField(null=True, verbose_name='最近活跃时间'),
        ),
        migrations.CreateModel(
            name='GitHubUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('github_user_id', models.CharField(blank=True, max_length=255, verbose_name='Github ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='github_user', to='arkid_meta.user', verbose_name='用户')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
