# Generated by Django 3.1.2 on 2020-11-01 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arkid_meta', '0003_auto_20201101_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubuser',
            name='wechat_user',
        ),
        migrations.AddField(
            model_name='wechatuser',
            name='github_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='github_user', to='arkid_meta.githubuser', verbose_name='github用户'),
            preserve_default=False,
        ),
    ]
