# Generated by ArkFBP 0.0.3.dev0 on 2020-10-14 06:20:20

from django.urls import path
from siteapi.v1.user.create_user.main import Main as siteapi_v1_user_create_user
from siteapi.v1.ucenter.login.with_password.main import Main as siteapi_v1_ucenter_login_with_password


urlpatterns = [
 path('siteapi/v1/user/', siteapi_v1_user_create_user.pre_as_view(http_method=['POST']), name='siteapi_v1_user_create_user'),
 path('siteapi/v1/ucenter/login/password/', siteapi_v1_ucenter_login_with_password.pre_as_view(http_method=['POST']), name='siteapi_v1_ucenter_login_with_password'),
 path('siteapi/v1/ucenter/login/password/', siteapi_v1_ucenter_login_with_password.pre_as_view(http_method=['PUT']),
      name='siteapi_v1_ucenter_login_with_password')

]
